# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: bookings
      MARIADB_USER: booker
      MARIADB_PASSWORD: haslo1
      

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


  api:
    image: webapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7500:7500

